### ISSUE TITLE
Order issue, gulp-order not solving it

### ISSUE THREAD

**Issue by newtonianb** [ahaurw01/gulp-remember#17]
I am trying to use gulp-order as stated is needed if order is to be respected. I am trying but gulp-order is not doing anything. I created the exact repo to outline the problem available here.

https://github.com/newtonianb/gulp-order-problem
`npm install && bower install && gulp js` and see output in `public/scripts.js`. The coffeescript file (a.coffee) is being concatenated after the js file (b.js) eventhough the order states a should come first.

I also asked in gulp-order but I'm wondering if there is some incompatibility recently introduced or if I'm doing something wrong?

```
'use strict';
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();

gulp.task('js', function (callback) {

    var coffeeFilter = $.filter(['**/*.coffee']);

    var src = [
        'resources/assets/bower/jquery/dist/jquery.min.js',
        'resources/assets/bower/jquery-migrate/jquery-migrate.min.js',
        'resources/assets/scripts/util/a.coffee',
        'resources/assets/scripts/b.js'
    ];

    var destName = 'scripts.js';
    var dest = 'public/assets';

    return gulp.src(src)

    .pipe(coffeeFilter)
    .pipe($.cached('coffee'))
    .pipe($.coffee())
    .pipe($.remember('coffee'))
    .pipe($.order(src, { base: process.cwd() }))
    .pipe(coffeeFilter.restore())

    .pipe($.concat(destName))
    .pipe(gulp.dest(dest));
});
```

**Comment by ahaurw01** [comment]
1. Your call to `order()` needs to go after your `coffeeFilter.restore()`, otherwise it is ordering only coffee files.
1. Your `order(...)` uses the `src` array as ordering instructions which hard-coded `a.coffee`. By the time gulp gets there, the path of the coffee file has changed to `resources/assets/scripts/util/a.js`, so `gulp-order` doesn't find it.
1. Use [`gulp-debug`](https://www.npmjs.com/package/gulp-debug) to find out what the files look like at a given step. E.g. `.pipe(debug())`.

(FYI this doesn't have anything to do with `gulp-remember`.)

Here is one working solution:

```js
'use strict';
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();

gulp.task('js', function (callback) {

    var coffeeFilter = $.filter(['**/*.coffee']);

    var src = [
        'resources/assets/bower/jquery/dist/jquery.min.js',
        'resources/assets/bower/jquery-migrate/jquery-migrate.min.js',
        'resources/assets/scripts/util/a.*', // don't hard-code .coffee
        'resources/assets/scripts/b.js'
    ];

    var destName = 'scripts.js';
    var dest = 'public/assets';

    return gulp.src(src)

    .pipe(coffeeFilter)
    .pipe($.cached('coffee'))
    .pipe($.coffee())
    .pipe($.remember('coffee'))
    .pipe(coffeeFilter.restore())
    .pipe($.order(src, { base: process.cwd() })) // order after removing coffee filter
    .pipe($.concat(destName))
    .pipe(gulp.dest(dest));
});
```
